package model.effect;

public enum ActionType {
    GAIN_MEMORY,
    INCREASE_DP,
    SECURITY_ATTACK,
    ACTIVATE_MAIN_EFFECT,
    PLAY_CARD,
    RESTRICT_OPPONENT_DIGIMON,
    DELETE_ONE_DIGIMON,
    DELETE_TWO_DIGIMON,
    DEFAULT
}
