package model.effect;

public enum EffectType {
    ON_PLAY, ON_DELETION,
    MAIN, SECURITY, RULE,
    WHEN_DIGIVOLVING, WHEN_ATTACKING,
    ALL_TURN, YOUR_TURN, OPPONENT_TURN,
    START_OF_YOUR_TURN, START_OF_YOUR_MAIN_PHASE, END_OF_ATTACK, END_OF_YOUR_TURN, END_OF_OPPONENT_TURN,
    ONCE_PER_TURN, TWICE_PER_TURN
}
